# Python Libraries (Numpy)

# Numpy Arrays

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [4]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,11,2) # arange is just like the range function use to quickly create an array 

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.zeros(3) # use to create a zero array 

array([0., 0., 0.])

In [8]:
np.zeros((5,5)) # for 2-dimensional array containing zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
# Simarlarly creating an array of only ones
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
# for 2-D array
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.linspace(0,5,100)

# Return evenly spaced numbers over a specified interval.
# Returns `num` evenly spaced samples, calculated over the
# interval [`start`, `stop`].

# The endpoint of the interval can optionally be excluded.

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [12]:
np.eye(4) # Identity Matrix which consist diagonal ones and rest zeros.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand(5)

array([0.33651778, 0.55324592, 0.47698501, 0.23291031, 0.50930802])

In [14]:
np.random.rand(5,5)
# Random method used to create a random 2-d array, uniformly distributed b/w 0 and 1.

array([[0.92675459, 0.81403003, 0.93994294, 0.3824143 , 0.50077023],
       [0.12057919, 0.07873712, 0.17886934, 0.34968523, 0.03643192],
       [0.93571617, 0.82521504, 0.17741765, 0.40577748, 0.86944964],
       [0.51729569, 0.25278543, 0.89092754, 0.31301529, 0.32164905],
       [0.55402224, 0.07270542, 0.44469956, 0.77719116, 0.9312922 ]])

In [15]:
np.random.randn(3) #Return a sample (or samples) from the "standard normal" distribution.

array([ 2.52303341,  0.6223466 , -0.57185768])

In [16]:
np.random.randint(1,100,10)
# randint(low, high=None, size=None, dtype=int)

# Return random integers from `low` (inclusive) to `high` (exclusive).

# Return random integers from the "discrete uniform" distribution of
# the specified dtype in the "half-open" interval [`low`, `high`).

array([18, 45, 40, 11,  6, 21, 82, 95, 80, 85])

In [17]:
arr = np.arange(25)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
ranarr = np.random.randint(0,50,10)

In [20]:
ranarr

array([34,  9,  4, 40, 16, 46, 14, 21,  9, 47])

In [21]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
ranarr.max() # To find the maximum value in the given array.

47

In [23]:
ranarr.min()# To find the minimum value in the given array.

4

In [24]:
ranarr.argmax()# returns the index values of the greatest no. in the array.

9

In [25]:
ranarr.argmin()# returns the index values of the smallest no. in the array.

2

In [26]:
arr.shape # returns shape or dimensions of array

(25,)

In [27]:
arr.dtype # returns the data type of the array

dtype('int32')

# NumPy Indexing and Selection

In [28]:
arr=np.arange(1,11)

In [29]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr[6]

7

In [31]:
arr[0:6]

array([1, 2, 3, 4, 5, 6])

In [32]:
arr[5:]

array([ 6,  7,  8,  9, 10])

In [33]:
arr[0:5]=100

In [34]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [35]:
arr = np.arange(0,11)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr[3]

3

In [38]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [39]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [40]:
arr[0:5]=120

In [41]:
arr

array([120, 120, 120, 120, 120,   5,   6,   7,   8,   9,  10])

In [42]:
arr = np.arange(0,11)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
slice_of_arr = arr[0:6]

In [45]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [46]:
slice_of_arr[:4]

array([0, 1, 2, 3])

In [47]:
slice_of_arr[:]=100

In [48]:
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [49]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [50]:
# 2-D array

In [51]:
arr_2d = np.array([[23,21,32],[12,23,34]])

In [52]:
arr_2d

array([[23, 21, 32],
       [12, 23, 34]])

In [53]:
arr_2d[1][0]

12

In [54]:
arr_2d[1]

array([12, 23, 34])

In [55]:
# Using slicing in 2-D array

In [56]:
arr_2d[:2,:2]

array([[23, 21],
       [12, 23]])

In [57]:
arr_2d = np.array([[23,21,32],[12,23,34],[45,56,67]])

In [58]:
arr_2d

array([[23, 21, 32],
       [12, 23, 34],
       [45, 56, 67]])

In [59]:
arr_2d[1:,:2]

array([[12, 23],
       [45, 56]])

In [60]:
# Conditional Selection
arr = np.arange(1,11)

In [61]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [63]:
bool_arr = arr > 5

In [64]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [65]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [66]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [67]:
arr_2d = np.arange(50).reshape(5,10)

In [68]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [69]:
# Now we have to slice the 2d array and get a 2-2 matrix 
# [[13,14]
#  [23,24]]

arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [70]:
# for 
# [[38,39]
#  [48,49]]

arr_2d[3:][8:]

array([], shape=(0, 10), dtype=int32)

In [71]:
arr_2d[3:,8:]

array([[38, 39],
       [48, 49]])

# Numpy Operations

-> Array with Array

-> Array with Scalars

-> Universal Array Functions

In [72]:
arr = np.arange(0,11)

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
# Array by array operations
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [75]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [76]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [77]:
# The warning generated is due the 0/0 division.
# In normal division anything divided by zero gives an error, but in numpy it still allow the code to execute
# and just throws a warning.
arr / arr

C:\Users\yatha\AppData\Local\Temp\ipykernel_5124\1058138461.py:4: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [78]:
# For array with scalars 
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [79]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [80]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [81]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [82]:
# Universal array function
np.sqrt(arr) # Square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [83]:
np.exp(arr) # exponential

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [84]:
np.max(arr) # Largest Value in array

10

In [85]:
np.sin(arr) # converting to sine 

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [86]:
np.log(arr) #logarithmic

C:\Users\yatha\AppData\Local\Temp\ipykernel_5124\2913640693.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) #logarithmic


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])